services:
  bot:
    build: .
    volumes:
      - ./.env:/root/.env
    env_file:
      - .env
    environment:
      - TZ=Asia/Tokyo
    command: ["go", "run", "main.go"]
    restart: unless-stopped
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
